[package]
name = "starship-server-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
async-graphql = "4.0.14"
async-graphql-actix-web = "4.0.14"
sqlx = "0.6.2"
tokio = "1.21.2"
