[package]
name = "toolbox-types"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.12"
nanoid = "0.4.0"
paste = "1.0.14"
