//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "planet")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub name: String,
    pub created: DateTime,
    pub owner: String,
    pub private: bool,
    pub member_count: i32,
    pub featured: bool,
    pub verified: bool,
    pub partnered: bool,
    pub featured_description: String,
    pub banned: Vec<String>,
    pub css: String,
    pub description: Option<String>,
    pub home: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::planet_component::Entity",
        from = "Column::Home",
        to = "super::planet_component::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PlanetComponent,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::Owner",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
    #[sea_orm(has_many = "super::planet_role::Entity")]
    PlanetRole,
    #[sea_orm(has_many = "super::custom_emoji::Entity")]
    CustomEmoji,
    #[sea_orm(has_many = "super::planet_member::Entity")]
    PlanetMember,
}

impl Related<super::planet_component::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlanetComponent.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::planet_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlanetRole.def()
    }
}

impl Related<super::custom_emoji::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomEmoji.def()
    }
}

impl Related<super::planet_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlanetMember.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
