CREATE TABLE planets (
  id TEXT PRIMARY KEY,
  created TIMESTAMP,
  name TEXT NOT NULL DEFAULT '',
  owner TEXT NOT NULL REFERENCES users(id),
  private BOOLEAN NOT NULL DEFAULT FALSE,
  follower_count INTEGER NOT NULL DEFAULT 0,

  components TEXT[] NOT NULL DEFAULT '{}',

  featured BOOLEAN NOT NULL DEFAULT FALSE,
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  partnered BOOLEAN NOT NULL DEFAULT FALSE,
  featured_description TEXT NOT NULL DEFAULT '',

  banned TEXT[] NOT NULL DEFAULT '{}',
  roles TEXT[] NOT NULL DEFAULT '{}',

  css TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT ''
)
